# GitHub Repository Data Cleaning

In [9]:
import pandas as pd

## Dataset Loading

In [10]:
data = r"..\data\raw\github_repositories_raw.csv"
github_df=pd.read_csv(data)

## Dataset Structure Check

In [11]:
github_df.head()

,owner,name,description,stars,forks,watchers,repo_size,language,created_at,updated_at,...,open_issues,license,topics,has_issues,has_wiki,has_discussions,archived,default_branch,visibility,url
0,PaddlePaddle,PaddlePaddle/PaddleOCR,Turn any PDF or image document into structured...,90276,11414,90276,1970859,Python,2020-05-08T10:38:16Z,2026-09-27T15:15:43Z,...,252,Apache-2.0,"['ai4science', 'chineseocr', 'document-parsing...",True,False,True,False,main,public,https://github.com/PaddlePaddle/PaddleOCR
1,Z4nzu,Z4nzu/hackingtool,ALL IN ONE Hacking Tool For Hackers,79775,9038,79775,6457,Python,2020-04-11T09:21:31Z,2026-09-27T15:24:53Z,...,134,MIT,"['allinonehackingtool', 'besthackingtool', 'ct...",True,True,False,False,master,public,https://github.com/Z4nzu/hackingtool
2,ultralytics,ultralytics/yolov5,Ultralytics YOLOv5 in PyTorch for object detec...,58091,17461,58091,18127,Python,2020-05-18T03:45:11Z,2026-09-27T09:35:42Z,...,31,AGPL-3.0,"['computer-vision', 'coreml', 'deep-learning',...",True,True,True,False,master,public,https://github.com/ultralytics/yolov5
3,SimplifyJobs,SimplifyJobs/Summer2027-Internships,"Summer 2027 software engineering, data science...",47720,3257,47720,4380013,Python,2020-05-23T20:53:18Z,2026-09-27T15:31:52Z,...,107,NaN,"['data-science', 'fall-2026', 'github', 'inter...",True,False,False,False,dev,public,https://github.com/SimplifyJobs/Summer2027-Int...
4,coqui-ai,coqui-ai/TTS,🐸💬 - a deep learning toolkit for Text-to-Speec...,46074,6162,46074,170196,Python,2020-05-20T15:45:28Z,2026-09-27T14:54:35Z,...,2,MPL-2.0,"['deep-learning', 'glow-tts', 'hifigan', 'melg...",True,True,True,False,dev,public,https://github.com/coqui-ai/TTS

In [12]:
github_df.shape

(5359, 21)

In [13]:
github_df.columns

Index(['owner', 'name', 'description', 'stars', 'forks', 'watchers',
       'repo_size', 'language', 'created_at', 'updated_at', 'created_year',
       'open_issues', 'license', 'topics', 'has_issues', 'has_wiki',
       'has_discussions', 'archived', 'default_branch', 'visibility', 'url'],
      dtype='str')

In [14]:
github_df.dtypes

owner                str
name                 str
description          str
stars              int64
forks              int64
watchers           int64
repo_size          int64
language             str
created_at           str
updated_at           str
created_year       int64
open_issues        int64
license              str
topics               str
has_issues          bool
has_wiki            bool
has_discussions     bool
archived            bool
default_branch       str
visibility           str
url                  str
dtype: object

In [15]:
github_df.isnull().sum()

owner                0
name                 0
description        106
stars                0
forks                0
watchers             0
repo_size            0
language             1
created_at           0
updated_at           0
created_year         0
open_issues          0
license            993
topics               0
has_issues           0
has_wiki             0
has_discussions      0
archived             0
default_branch       0
visibility           0
url                  0
dtype: int64

In [16]:
print(github_df.duplicated().sum())

0

## Missing Value Treatment

In [17]:
github_df[["description","license"]]=github_df[["description","license"]].fillna("Unknown")

In [18]:
github_df["language"]=github_df["language"].fillna("Python")

## Missing Value Verification

In [19]:
github_df.isnull().sum()

owner              0
name               0
description        0
stars              0
forks              0
watchers           0
repo_size          0
language           0
created_at         0
updated_at         0
created_year       0
open_issues        0
license            0
topics             0
has_issues         0
has_wiki           0
has_discussions    0
archived           0
default_branch     0
visibility         0
url                0
dtype: int64

## Data Type Conversion

In [20]:
github_df["created_at"]=pd.to_datetime(github_df["created_at"])

In [21]:
github_df["updated_at"]=pd.to_datetime(github_df["updated_at"])

In [22]:
github_df.dtypes

owner                              str
name                               str
description                        str
stars                            int64
forks                            int64
watchers                         int64
repo_size                        int64
language                           str
created_at         datetime64[us, UTC]
updated_at         datetime64[us, UTC]
created_year                     int64
open_issues                      int64
license                            str
topics                             str
has_issues                        bool
has_wiki                          bool
has_discussions                   bool
archived                          bool
default_branch                     str
visibility                         str
url                                str
dtype: object

## Numerical Data Validation

In [23]:
columns = github_df.select_dtypes(include=["number"]).columns.tolist()
for column in columns:
    if column=="created_year":
        invalid_year = (github_df[column] > 2026) |( github_df[column] < 2020)
        print(f"Invalid {column}:",invalid_year.sum())
    else:
        invalid_=github_df[column]<0
        print(f"Invalid {column}:",invalid_.sum())

Invalid stars: 0
Invalid forks: 0
Invalid watchers: 0
Invalid repo_size: 0
Invalid created_year: 0
Invalid open_issues: 0

## Date Consistency

In [24]:
inconsistent_date=github_df["created_at"]>github_df["updated_at"]
print(inconsistent_date.sum())

0

## Categorical Data Consistency

In [25]:
categorical_col=["language","license","visibility","default_branch"]
for col in categorical_col:
    unique=github_df[col].nunique()
    print(f"Unique Values in {col}:",unique)
    print(github_df[col].value_counts())
    print()

Unique Values in language: 1
language
Python    5359
Name: count, dtype: int64

Unique Values in license: 24
license
MIT                   2146
Apache-2.0            1144
Unknown                993
NOASSERTION            380
GPL-3.0                288
AGPL-3.0               139
BSD-3-Clause           122
BSD-2-Clause            27
GPL-2.0                 20
CC0-1.0                 18
LGPL-3.0                16
CC-BY-4.0               12
MPL-2.0                 11
CC-BY-SA-4.0             8
Unlicense                8
LGPL-2.1                 7
MIT-0                    6
BSD-3-Clause-Clear       4
WTFPL                    3
OFL-1.1                  2
ISC                      2
0BSD                     1
Artistic-2.0             1
UPL-1.0                  1
Name: count, dtype: int64

Unique Values in visibility: 1
visibility
public    5359
Name: count, dtype: int64

Unique Values in default_branch: 70
default_branch
main                                 4045
master                               1169
develop                                40
dev                                    27
devel                                   4
                                     ...
TrenTorch-Dev                           1
standalone                              1
windows-claudecode                      1
computer-use-automation-take-home       1
claude/practical-hopper-i6hsy1          1
Name: count, Length: 70, dtype: int64

## Outlier Detection

In [26]:
categories = ["stars", "forks", "watchers", "repo_size", "open_issues"]

In [27]:
Q1=github_df[categories].quantile(0.25)
Q3=github_df[categories].quantile(0.75)
print("Q1:\n",Q1)
print("Q3:\n",Q3)

Q1:
 stars           11.0
forks            1.0
watchers        11.0
repo_size      550.0
open_issues      0.0
Name: 0.25, dtype: float64
Q3:
 stars           2986.5
forks            285.5
watchers        2986.5
repo_size      32145.5
open_issues       27.0
Name: 0.75, dtype: float64

In [28]:
IQR=Q3-Q1
print("IQR:\n",IQR)

IQR:
 stars           2975.5
forks            284.5
watchers        2975.5
repo_size      31595.5
open_issues       27.0
dtype: float64

In [29]:
lower_limit=Q1-1.5*IQR
upper_limit=Q3+1.5*IQR
print("Lower Limit:\n",lower_limit)
print("Upper Limit:\n",upper_limit)

Lower Limit:
 stars          -4452.25
forks           -425.75
watchers       -4452.25
repo_size     -46843.25
open_issues      -40.50
dtype: float64
Upper Limit:
 stars           7449.75
forks            712.25
watchers        7449.75
repo_size      79538.75
open_issues       67.50
dtype: float64

In [30]:
for category in categories:
    outliers=github_df[(github_df[category]<lower_limit[category]) | ( github_df[category]>upper_limit[category])]
    print(f"Outliers in {category}: {len(outliers)}")

Outliers in stars: 787
Outliers in forks: 880
Outliers in watchers: 787
Outliers in repo_size: 754
Outliers in open_issues: 863

## Relationship Consistency

In [31]:
forks_vs_stars=github_df["forks"]>github_df["stars"]
print(forks_vs_stars.sum())

50

In [32]:
watchers_vs_stars=github_df["watchers"]!=github_df["stars"]
print(watchers_vs_stars.sum())

0

### Forks Greater Than Stars Inspection

In [33]:
github_df[forks_vs_stars][["name","stars","forks","watchers","url"]]

,name,stars,forks,watchers,url
249,Kalebu/Real-time-Vehicle-Dection-Python,37,38,37,https://github.com/Kalebu/Real-time-Vehicle-De...
313,roerohan/CTF-Write-ups,6,18,6,https://github.com/roerohan/CTF-Write-ups
343,rzr/awox-mesh-light-webthing,1,2,1,https://github.com/rzr/awox-mesh-light-webthing
641,codingforentrepreneurs/Try-Django-3.2,345,427,345,https://github.com/codingforentrepreneurs/Try-...
656,bislara/code-n-stitch,46,84,46,https://github.com/bislara/code-n-stitch
663,Descent098/ezcv,16,34,16,https://github.com/Descent098/ezcv
684,douglasdaly/web-app-skeleton,4,6,4,https://github.com/douglasdaly/web-app-skeleton
723,LaMenteOcupada/Python-Scrapper-playlist,1,2,1,https://github.com/LaMenteOcupada/Python-Scrap...
980,Andrew-FungKinHo/YouTube,31,36,31,https://github.com/Andrew-FungKinHo/YouTube
1048,a7medayman6/Todo-List-Dockerized-Flask-WebApp,7,86,7,https://github.com/a7medayman6/Todo-List-Docke...
1053,krypton-byte/OnlineIDE,5,7,5,https://github.com/krypton-byte/OnlineIDE
1067,Nelson-Gon/urlfix,3,8,3,https://github.com/Nelson-Gon/urlfix
1103,Coroxx/WebAnalyst,1,2,1,https://github.com/Coroxx/WebAnalyst
1168,anasty17/mirror-leech-telegram-bot,4311,5118,4311,https://github.com/anasty17/mirror-leech-teleg...
1268,IBM/LNN,333,474,333,https://github.com/IBM/LNN
1368,bdpedigo/networks-course,22,26,22,https://github.com/bdpedigo/networks-course
1450,jkuatdsc/dscjkuat-web,2,3,2,https://github.com/jkuatdsc/dscjkuat-web
1456,davep/ng2web,2,3,2,https://github.com/davep/ng2web
1480,muhammetsahinadibas/requester,1,2,1,https://github.com/muhammetsahinadibas/requester
1491,Nenma/wade-gat,0,1,0,https://github.com/Nenma/wade-gat
1935,digitalinnovationone/trilha-python-dio,5126,7124,5126,https://github.com/digitalinnovationone/trilha...
2158,jvm-coder/Hacktoberfest2022_aakash,48,216,48,https://github.com/jvm-coder/Hacktoberfest2022...
2166,crazycodigo/Coding-Basics-HacktoberFest2022,17,114,17,https://github.com/crazycodigo/Coding-Basics-H...
2201,Suruchi2310/hacktoberfest2022-beginner,3,22,3,https://github.com/Suruchi2310/hacktoberfest20...
2212,Firdavs-coder/free-templates-uz,2,3,2,https://github.com/Firdavs-coder/free-template...
2325,iam-veeramalla/aws-devops-zero-to-hero,11561,15692,11561,https://github.com/iam-veeramalla/aws-devops-z...
2335,iam-veeramalla/Jenkins-Zero-To-Hero,10057,19691,10057,https://github.com/iam-veeramalla/Jenkins-Zero...
2529,PhilippVerpoort/posted,10,14,10,https://github.com/PhilippVerpoort/posted
2608,DogukanUrker/flaskToDo,2,6,2,https://github.com/DogukanUrker/flaskToDo
2629,TrueRou/nogu,1,2,1,https://github.com/TrueRou/nogu
2919,canbula/DataScience,7,19,7,https://github.com/canbula/DataScience
2958,eclipse-thingweb/domus-tdd-api,7,9,7,https://github.com/eclipse-thingweb/domus-tdd-api
3003,dev-bittu/QuizApp-Flask,2,3,2,https://github.com/dev-bittu/QuizApp-Flask
3302,AICLUB-IIITDM/data-science-bootcamp-2024,5,89,5,https://github.com/AICLUB-IIITDM/data-science-...
3700,lispringing/SuperStar,307,514,307,https://github.com/lispringing/SuperStar
3945,kubeflow/sdk,149,264,149,https://github.com/kubeflow/sdk
4044,rt-adesai/rt-repo-assessment,11,15,11,https://github.com/rt-adesai/rt-repo-assessment
4131,angrysky56/mcp-windows-website-downloader,6,8,6,https://github.com/angrysky56/mcp-windows-webs...
4353,pyfenn/fenn,82,83,82,https://github.com/pyfenn/fenn
4546,kenjisubagja/octra-auto,2,3,2,https://github.com/kenjisubagja/octra-auto
4784,im-anishraj/arnio,96,383,96,https://github.com/im-anishraj/arnio
4815,Khanz9664/TrustLens,16,21,16,https://github.com/Khanz9664/TrustLens
4826,hiero-hackers/analytics,13,26,13,https://github.com/hiero-hackers/analytics
4836,PhilanthroPy-Project/PhilanthroPy,11,22,11,https://github.com/PhilanthroPy-Project/Philan...
4906,yourworstnightmare1/proxy-list,7,16,7,https://github.com/yourworstnightmare1/proxy-list
5015,Rion-Wu-tech/wechat-intelligence-hub,2553,2730,2553,https://github.com/Rion-Wu-tech/wechat-intelli...
5060,amirh00sain/SpiderPanel,1520,5542,1520,https://github.com/amirh00sain/SpiderPanel
5155,bijay-odyssey/edaprep,15,23,15,https://github.com/bijay-odyssey/edaprep
5159,tenstorrent/vllm-tt-plugin,14,16,14,https://github.com/tenstorrent/vllm-tt-plugin
5221,DataWithSoumya/retail-supply-chain-analytics,3,5,3,https://github.com/DataWithSoumya/retail-suppl...

## Cleaned Dataset Export

In [34]:
github_df.to_csv(r"..\data\processed\github_repositories_cleaned.csv",index=False)